########~~~~-- Stages --~~~~########

stages:
  - secure
  - test
  - update
  - build
  - internal
  - release

########~~~~-- Variables & defaults --~~~~########

variables:
  IMAGE: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alvrme/alpine-android:android-35-jdk21"
  JACOCO_PATH: "app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
  ANDROID_API_IMAGE: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/fabernovel/android:api-35-v1.10.1"
  GITLAB_CI_VERSION: "1.79.0"

default:
  image: $IMAGE
  interruptible: true

########~~~~-- Workflows --~~~~########

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_PIPELINE_SOURCE == 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

########~~~~-- Includes --~~~~########

include:
  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/secret-finder/secret-finder@main"
    inputs:
      job_name: "find_secrets"
      stage_config: "secure"

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "update"
      stage_config: "update"
      branch_name: "chore/update-dependencies"
      command: "./gradlew wrapper --gradle-version latest && ./gradlew useLatestVersions"
      commit_message: "⚙️ Update dependencies automatically"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: true

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "increment_major"
      stage_config: "update"
      branch_name: "chore/update-version"
      command: "./scripts/increment-version.sh major"
      commit_message: "🔖 Increment major version"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: no

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "increment_minor"
      stage_config: "update"
      branch_name: "chore/update-version"
      command: "./scripts/increment-version.sh minor"
      commit_message: "🔖 Increment minor version"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: no

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "increment_patch"
      stage_config: "update"
      branch_name: "chore/update-version"
      command: "./scripts/increment-version.sh patch"
      commit_message: "🔖 Increment patch version"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: no

find_secrets:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

update:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_UPDATE == 'true'"

increment_major:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_INCREMENT_MAJOR == 'true'"

increment_minor:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_INCREMENT_MINOR == 'true'"

increment_patch:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_INCREMENT_PATCH == 'true'"

########~~~~-- Jobs --~~~~########

run_unit_tests:
  stage: test
  script: ./gradlew test jacocoTestReport
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: $JACOCO_PATH
    paths:
      - app/build/reports/jacoco/
    expire_in: 1 week
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: find_secrets
      optional: true

analyze:
  stage: test
  image:
    name: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/sonarsource/sonar-scanner-cli:latest"
    entrypoint: [ "" ]
  cache:
    key: "${CI_JOB_NAME}"
    paths: [ .sonar/cache ]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - git config --global --add safe.directory "/builds/$CI_PROJECT_PATH"
    - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then PROJECT_VERSION=$LATEST_TAG; else PROJECT_VERSION=$LATEST_TAG-$CI_MERGE_REQUEST_ID; fi
    - sonar-scanner
      -Dsonar.projectVersion=$PROJECT_VERSION
      -Dsonar.projectKey="beavuck-services_stop-and-go"
      -Dsonar.organization="beavuck-services"
      -Dsonar.coverage.exclusions="app/src/androidTest/**,app/src/test/**,app/src/main/res/**,app/src/main/java/com/beavuck/stop_and_go/accessibility/**,app/src/main/java/com/beavuck/stop_and_go/gestures/**,app/src/main/java/com/beavuck/stop_and_go/settings/**,app/src/main/java/com/beavuck/stop_and_go/timer/**,app/src/main/java/com/beavuck/stop_and_go/ui/**,app/src/main/java/com/beavuck/stop_and_go/activities/**,app/src/main/java/com/beavuck/stop_and_go/repositories/**,app/src/main/java/com/beavuck/stop_and_go/dialogs/**,app/src/main/java/com/beavuck/stop_and_go/notifications/**,app/src/main/java/com/beavuck/stop_and_go/model/TimerConstants.kt,app/src/main/java/com/beavuck/stop_and_go/utils/ScreenManager.kt,app/src/main/java/com/beavuck/stop_and_go/utils/DebugUtils.kt,app/src/main/java/com/beavuck/stop_and_go/utils/ColorUtils.kt,app/src/main/AndroidManifest.xml"
      -Dsonar.sources="app/src/main/java"
      -Dsonar.coverage.jacoco.xmlReportPaths="$JACOCO_PATH"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
  needs:
    - job: find_secrets
    - job: run_unit_tests
      artifacts: true

build:
  image: $ANDROID_API_IMAGE
  stage: build
  cache:
    key: gems-cache
    paths:
      - vendor/bundle
  script:
    - apt update -y && apt install -y curl ruby-full build-essential
    - gem install bundler -N
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - wget https://gitlab.com/gitlab-org/cli/-/releases/v$GITLAB_CI_VERSION/downloads/glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - apt install ./glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
    - glab securefile download --all --output-dir .secure_files/
    - bundle exec fastlane build
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab
      - app/build/outputs/apk/release/app-release.apk
    expire_in: 1 week
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
  needs:
    - job: find_secrets
      optional: true
    - job: run_unit_tests
      optional: true

internal:
  image: $ANDROID_API_IMAGE
  stage: internal
  cache:
    key: gems-cache
    paths:
      - vendor/bundle
  script:
    - apt update -y && apt install -y curl ruby-full build-essential
    - gem install bundler -N
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - wget https://gitlab.com/gitlab-org/cli/-/releases/v$GITLAB_CI_VERSION/downloads/glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - apt install ./glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
    - glab securefile download --all --output-dir .secure_files/
    - bundle exec fastlane internal
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
      when: manual
  needs:
    - job: build
      artifacts: true

release:
  image: $ANDROID_API_IMAGE
  stage: release
  cache:
    key: gems-cache
    paths:
      - vendor/bundle
  script:
    - apt update -y && apt install -y curl ruby-full build-essential
    - gem install bundler -N
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - wget https://gitlab.com/gitlab-org/cli/-/releases/v$GITLAB_CI_VERSION/downloads/glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - apt install ./glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
    - glab securefile download --all --output-dir .secure_files/
    - bundle exec fastlane release
  rules:
    - if: "$CI_COMMIT_TAG"
      when: manual
  needs:
    - job: build
      artifacts: true
