########~~~~-- Stages --~~~~########

stages:
  - secure
  - test
  - upgrade
  - build
  - deploy

########~~~~-- Variables & defaults --~~~~########

variables:
  GITLAB_CI_VERSION: "1.91.0"
  FABERNOVEL_ANDROID_IMAGE: "api-35-v1.11.0"
  ALVRME_ANDROID_IMAGE: "android-35-jdk21"
  IMAGE: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alvrme/alpine-android:${ALVRME_ANDROID_IMAGE}"
  JACOCO_PATH: "app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"

default:
  image: $IMAGE
  interruptible: true

########~~~~-- Workflows --~~~~########

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_PIPELINE_SOURCE == 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

########~~~~-- Includes --~~~~########

include:
  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/secret-finder/secret-finder@main"
    inputs:
      job_name: "find_secrets"
      stage_config: "secure"

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "upgrade"
      stage_config: "upgrade"
      branch_name: "chore/upgrade-dependencies"
      command: "./gradlew wrapper --gradle-version latest && ./gradlew useLatestVersions && ./scripts/increment_version.sh patch"
      commit_message: "⚙️ Upgrade dependencies automatically"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: true

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "increment_version"
      stage_config: "upgrade"
      branch_name: "chore/upgrade-version"
      command: |
        if [ "$IS_INCREMENT_MAJOR" == "true" ]; then
          ./scripts/increment-version.sh major
        elif [ "$IS_INCREMENT_MINOR" == "true" ]; then
          ./scripts/increment-version.sh minor
        elif [ "$IS_INCREMENT_PATCH" == "true" ]; then
          ./scripts/increment-version.sh patch
        fi
      commit_message: "🔖 Increment version"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: no

find_secrets:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

upgrade:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_UPDATE == 'true'"

increment_version:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && ($IS_INCREMENT_MAJOR == 'true' || $IS_INCREMENT_MINOR == 'true' || $IS_INCREMENT_PATCH == 'true')"

########~~~~-- Job Templates --~~~~########

.fastlane_setup:
  image: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/fabernovel/android:${FABERNOVEL_ANDROID_IMAGE}"
  cache:
    key: gems-cache
    paths:
      - vendor/bundle
  before_script:
    - apt update -y && apt install -y curl ruby-full build-essential
    - gem install bundler -N
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - wget "https://gitlab.com/gitlab-org/cli/-/releases/v${GITLAB_CI_VERSION}/downloads/glab_${GITLAB_CI_VERSION}_linux_amd64.deb"
    - apt install -y ./glab_${GITLAB_CI_VERSION}_linux_amd64.deb
    - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
    - glab securefile download --all --output-dir .secure_files/

########~~~~-- Jobs --~~~~########

run_unit_tests:
  stage: test
  script: ./gradlew test jacocoTestReport
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: $JACOCO_PATH
    paths:
      - app/build/reports/jacoco/
    expire_in: 1 week
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
  needs:
    - job: find_secrets

analyze:
  stage: test
  image:
    name: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/sonarsource/sonar-scanner-cli:latest"
    entrypoint: [ "" ]
  cache:
    key: "${CI_JOB_NAME}"
    paths: [ .sonar/cache ]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - git config --global --add safe.directory "/builds/$CI_PROJECT_PATH"
    - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then PROJECT_VERSION=$LATEST_TAG; else PROJECT_VERSION=$LATEST_TAG-$CI_MERGE_REQUEST_ID; fi
    - sonar-scanner
      -Dsonar.projectVersion=$PROJECT_VERSION
      -Dsonar.projectKey="beavuck-services_stop-and-go"
      -Dsonar.organization="beavuck-services"
      -Dsonar.coverage.exclusions="app/src/androidTest/**,app/src/test/**,app/src/main/res/**,app/src/main/java/com/beavuck/stop_and_go/model/timer/**,app/src/main/java/com/beavuck/stop_and_go/ui/**,app/src/main/java/com/beavuck/stop_and_go/activities/**,app/src/main/java/com/beavuck/stop_and_go/repositories/**,app/src/main/java/com/beavuck/stop_and_go/dialogs/**,app/src/main/java/com/beavuck/stop_and_go/sounds/**,app/src/main/java/com/beavuck/stop_and_go/utils/instrumented/**,app/src/main/java/com/beavuck/stop_and_go/config/**,app/src/main/AndroidManifest.xml"
      -Dsonar.sources="app/src/main/java"
      -Dsonar.coverage.jacoco.xmlReportPaths="$JACOCO_PATH"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
  needs:
    - job: find_secrets
    - job: run_unit_tests
      artifacts: true

build:
  extends: .fastlane_setup
  stage: build
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/mapping/release/mapping.txt
      - app/build/outputs/native-debug-symbols/release/native-debug-symbols.zip
    expire_in: 1 week
  rules:
    - if: "$CI_COMMIT_TAG"

upload_package:
  stage: deploy
  image: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/curlimages/curl:latest"
  script:
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
        --upload-file app/build/outputs/apk/release/app-release.apk \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/stop-and-go/${CI_COMMIT_TAG}/stop-and-go-${CI_COMMIT_TAG}.apk"
  rules:
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: build
      artifacts: true

release_stop_and_go:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - apk add --no-cache curl git bash
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
    - PREV_TAG=$(git describe --tags --abbrev=0 "${CI_COMMIT_TAG}^")
    - RELEASE_DESCRIPTION=$(bash scripts/list_changes.sh "$PREV_TAG" "$CI_COMMIT_TAG")
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "$RELEASE_DESCRIPTION"
    assets:
      links:
        - name: "stop-and-go-${CI_COMMIT_TAG}.apk"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/stop-and-go/${CI_COMMIT_TAG}/stop-and-go-${CI_COMMIT_TAG}.apk"
          link_type: "package"
  rules:
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: upload_package

deploy:
  extends: .fastlane_setup
  stage: deploy
  script:
    - bundle exec fastlane internal
  rules:
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: build
      artifacts: true
