########~~~~-- Stages --~~~~########

stages:
  - secure
  - test
  - update

########~~~~-- Variables & defaults --~~~~########

variables:
  IMAGE: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alvrme/alpine-android:android-36-jdk21"
  JACOCO_PATH: "app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"

default:
  image: $IMAGE
  interruptible: true

########~~~~-- Workflows --~~~~########

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_PIPELINE_SOURCE == 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

########~~~~-- Includes --~~~~########

include:
  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/secret-finder/secret-finder@main"
    inputs:
      job_name: "find_secrets"
      stage_config: "secure"

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "update"
      stage_config: "update"
      branch_name: "chore/update-dependencies"
      command: "./gradlew wrapper --gradle-version latest && ./gradlew useLatestVersions"
      commit_message: "⚙️ Update dependencies automatically"
      image: "$IMAGE"
      script_to_install_deps: "apk add --no-cache bash curl jq git"
      consecutive_command_commits_allowed: true

find_secrets:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

update:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_UPDATE == 'true'"

########~~~~-- Jobs --~~~~########

run_unit_tests:
  stage: test
  script: ./gradlew test jacocoTestReport
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: $JACOCO_PATH
    paths:
      - app/build/reports/jacoco/
    expire_in: 1 week
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: find_secrets
      optional: true

analyze:
  stage: test
  image:
    name: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/sonarsource/sonar-scanner-cli:latest"
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths: [.sonar/cache]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - git config --global --add safe.directory "/builds/$CI_PROJECT_PATH"
    - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then PROJECT_VERSION=$LATEST_TAG; else PROJECT_VERSION=$LATEST_TAG-$CI_MERGE_REQUEST_ID; fi
    - sonar-scanner
      -Dsonar.projectVersion=$PROJECT_VERSION
      -Dsonar.projectKey="beavuck-services_stop-and-go"
      -Dsonar.organization="beavuck-services"
      -Dsonar.coverage.exclusions="app/src/androidTest/**,app/src/test/**,app/src/main/res/**,app/src/main/java/com/beavuck/stop_and_go/activities/**,app/src/main/AndroidManifest.xml"
      -Dsonar.sources="app/src/main/java"
      -Dsonar.coverage.jacoco.xmlReportPaths="$JACOCO_PATH"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
  needs:
    - job: find_secrets
    - job: run_unit_tests
      artifacts: true