default_platform(:android)

desc "Update version name and code based on the CI_COMMIT_TAG environment variable"
lane :update_version do
    tag = ENV['CI_COMMIT_TAG']
    if tag
        version_name = tag.gsub(/^v/, '')
        increment_version_code(
            gradle_file_path: "app/build.gradle.kts"
        )
        android_set_version_name(
            version_name: version_name,
            gradle_file: "app/build.gradle.kts"
        )
    else
        UI.user_error!("CI_COMMIT_TAG environment variable is not set")
    end
end

desc "Create and sign a new build"
lane :build do
    gradle(tasks: ["clean", "assembleRelease", "bundleRelease"])
end

desc "Submit a new Beta build to the Google Play store"
lane :beta do
    upload_to_play_store(
        track: 'internal',
        aab: 'app/build/outputs/bundle/release/app-release.aab',
        release_status: 'draft',
        json_key: '.secure_files/play-store-credentials.json'
    )
end

desc "Submit a new Production build to the Google Play store"
lane :release do
    upload_to_play_store(
        track: 'production',
        aab: 'app/build/outputs/bundle/release/app-release.aab',
        json_key: '.secure_files/play-store-credentials.json'
    )
end
